---
title: "Usage statistics"
date: '`r format(Sys.time(), format = "%Y-%m-%d %H:%M %Z")`'
---

```{r settings, echo = FALSE}
VersionPalette <- function(minor) {
  setNames(hcl.colors(6, switch(as.character(minor),
         "3.3" = "Reds 3",
         "3.4" = "Peach",
         "3.5" = "BrwnYl", 
         "3.6" = "Burg", 
         "4.0" = "Emrld",
         "4.1" = "Purp", 
         "4.2" = "Light Grays",
         "4.3" = "TealGrn",
         "4.4" = "Mint",
         "4.5" = "BuPu",
         "4.6" = "SunsetDark",
         "4.7" = "Peach",
         "Earth")),
         paste0(minor, ".", 0:5))
}
rCols <- unlist(lapply(c(seq(3.1, 3.6, 0.1), "4.0", c(seq(4.1, 4.7, 0.1))),
                  VersionPalette))
```

```{r read-logs, echo = FALSE}
downloads <- do.call(rbind, 
                     lapply(list.files("logs", full.names = TRUE), read.csv))
downloads$month <- substr(downloads[["date"]], 1, 7)
```

```{r function-definitions, echo = FALSE}
SummaryBlock <- function(packageName) {
  cat(paste("\n\n##", packageName, "\n"))
  pkg <- downloads[downloads[["package"]] == packageName, ]
  pkg[["version"]] <- gsub("\\.tar\\.gz.*", "", pkg[["version"]])
  
  
  tab <- table(pkg[, c("r_version", "month")])
  par(mar = c(5, 3, 0.1, 0.1))
  barplot(tab, col = rCols[rownames(tab)], las = 2)
  majors <- unique(substr(rownames(tab)[rowSums(tab) > 10], 1, 3))
  legend("topright", majors, pch = 15, col = rCols[paste0(majors, ".2")],
         ncol = 2, xpd = NA, cex = 0.8, title = "R version")
  
  
  tab <- table(pkg[, c("version", "month")])
  versions <- as.package_version(rownames(tab))
  tab <- tab[order(versions), ]
  par(mar = c(5, 3, 0.1, 0.1))
  vPal <- rep(hcl.colors(8, "Temps"), length.out = nrow(tab))
  bp <- barplot(tab, las = 2, col = vPal)
  legend("topright", rev(rownames(tab)), pch = 15, col = rev(vPal),
         ncol = 2, xpd = NA, cex = 0.8, bty = "n", title = "Package version")
}
```

Downloads with no R version information are excluded from the respective
summary plots.

```{r package-statistics, echo = FALSE, results = "asis"}
invisible(lapply(sort(unique(downloads$package)), SummaryBlock))
```
